
# -*- coding: utf-8 -*-
# @Time    : 2023/3/24 12:45
# @Author  : wangchuan7
# @FileName: test.py
# @Software: PyCharm
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
# -*- coding: utf-8 -*-
# @Time    : 2023/3/24 12:45
# @Author  : wangchuan7
# @FileName: test.py
# @Software: PyCharm
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
# -*- coding: utf-8 -*-
# @Time    : 2023/3/24 12:45
# @Author  : wangchuan7
# @FileName: test.py
# @Software: PyCharm
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
# -*- coding: utf-8 -*-
# @Time    : 2023/3/24 12:45
# @Author  : wangchuan7
# @FileName: test.py
# @Software: PyCharm
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
# -*- coding: utf-8 -*-
# @Time    : 2023/3/24 12:45
# @Author  : wangchuan7
# @FileName: test.py
# @Software: PyCharm
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
# -*- coding: utf-8 -*-
# @Time    : 2023/3/24 12:45
# @Author  : wangchuan7
# @FileName: test.py
# @Software: PyCharm
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
# -*- coding: utf-8 -*-
# @Time    : 2023/3/24 12:45
# @Author  : wangchuan7
# @FileName: test.py
# @Software: PyCharm
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
# -*- coding: utf-8 -*-
# @Time    : 2023/3/24 12:45
# @Author  : wangchuan7
# @FileName: test.py
# @Software: PyCharm
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
print ("www.pt.xiaomi.com")
print ("relay.xiaomi.com")
print ("login.mioffice.cn")
print ("b2c.srv")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")
print ("api.xiaomi.com")
print ("youpin.mi.com")
print ("api.mi.com")
print ("proxy.srv")
print ("test.xiaomi.proxy.srv")
print ("test.xiaomi.srv")
print ("11.xiaomi.srv")
print ("112.xiaomi.srv")
print ("112hello.xiaomi.srv")
print ("test query xiaomi")
print ("test.b2c.srv")
print ("test.b2c.srv.mioffice.cn")